{% set name = "spfluo-app" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: file:///home/plumail/code/spfluo-app/dist/spfluo-app-0.1.tar.gz
    target: spfluo-app

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7,<3.12
    # -c local
    - scipion-app
    - scipion-fluo-singleparticle

test:
  imports:
    - spfluo

about:
  summary: SPFluo package

extra:
  recipe-maintainers:
    - jplumail
