[lint]
select = [
    "E", "F", # default
    "I", # isort
]

[lint.isort]
known-first-party = ["spfluo"]

[lint.per-file-ignores]
"spfluo/picking/*" = ["E501"]
"spfluo/segmentation/unet_3d.py" = ["E501"]
"spfluo/segmentation/losses.py" = ["E501"]
"spfluo/_vendored/*" = ["ALL"]

[format]
exclude = ["spfluo/_vendored/*"]
