[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scipion-pyworkflow"
version = "0.0.1"  # wrong version
description = "Simple workflow platform used in scientific applications, initially developed within the Scipion framework for image processing in Electron Microscopy."
readme = "README.rst"
requires-python = ">=3.8"
keywords = ["workflows", "science", "electron-microscopy", "cryo-em", "structural-biology", "image-processing", "scipion"]
authors = [
    {name = "J.M. De la Rosa Trevin", email = "delarosatrevin@scilifelab.se"},
    {name = "Roberto Marabini", email = "roberto@cnb.csic.es"},
    {name = "Grigory Sharov", email = "gsharov@mrc-lmb.cam.ac.uk"},
    {name = "Josue Gomez Blanco", email = "josue.gomez-blanco@mcgill.ca"},
    {name = "Pablo Conesa", email = "pconesa@cnb.csic.es"},
    {name = "Yunior Fonseca Reyna", email = "fonsecareyna@cnb.csic.es"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]

dependencies = [
    "bibtexparser",
    "psutil",
    "configparser",
    "matplotlib",
    "numpy",
    "requests",
    "pillow",
    "tkcolorpicker",
    "distro",
    "importlib-metadata"
]

[project.urls]
"Homepage" = "https://github.com/scipion-em/scipion-pyworkflow"
"Bug Reports" = "https://github.com/scipion-em/scipion-pyworkflow/issues"
"Source" = "https://github.com/scipion-em/scipion-pyworkflow/"

[project.scripts]
fix_links = "pyworkflow.project.scripts.fix_links:main"

[project.entry-points."pyworkflow.plugin"]
pyworkflowtests = "pyworkflowtests"

[tool.setuptools.package-data]
"pyworkflow" = ["resources/*", "project/scripts/*"]

[tool.setuptools.packages.find]
exclude = ["pyworkflowtests"]