{% set name = "scipion-app" %}
{% set version = "3.3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://vps-429048d2.vps.ovh.net/jean/dev/+f/050/0486326a8ec94/scipion-app-3.3.0.tar.gz
    sha256: 0500486326a8ec94dba61e752182c6181d42d5df2ee59ff0f82ced0351874d00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7,<3.12
    # -c local
    - scipion-fluo
    - outdated =0.2.2
    # -c conda-forge
    - typing_extensions