{% set name = "scipion-pyworkflow" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://vps-429048d2.vps.ovh.net/jean/dev/+f/ba3/ead820ab8bcd1/scipion-pyworkflow-3.3.0.tar.gz
    sha256: ba3ead820ab8bcd1ef54f7b3ffe3ab78434f93b3d84f6d1e943069d091ce2c74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7,<3.12
    # -c conda-forge
    - bibtexparser <=1.2.0
    - psutil
    - configparser
    - matplotlib-base
    - numpy
    - pillow
    - requests
    # -c jplumail
    - tkcolorpicker

test:
  imports:
    - pyworkflow