{% set name = "spfluo" %}
{% set version = "0.1b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://vps-429048d2.vps.ovh.net/jean/dev/+f/4c2/4a05034dc5ef0/spfluo-0.1b3.tar.gz
    sha256: 4c24a05034dc5ef0bb940c6d0170907d6b2269a0ebd9863743f1cb099025951d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  
requirements:
  host:
    - python >=3.7,<3.12
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7,<3.12
# -c pytorch -c nvidia
    - pytorch
    - pytorch-cuda
# -c conda-forge
    - cupy
    - simpleitk
    - pynvml
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - tqdm
    - matplotlib
    - pooch
    - napari >=0.4.18
    - pyqt
    - napari-aicsimageio
    - tifffile <2023.3.15 # broken napari-aicsimageio dep
    - pandas
    # pandas is broken with napari-aicsimageio, need to add these deps:
    - ome-zarr
    - xmlschema
    - xarray <2023.02.0,>=0.16.1
# -c local
    - cucim

test:
  imports:
    - spfluo

about:
  summary: SPFluo package

extra:
  recipe-maintainers:
    - jplumail
