FLUO_ROOT_VAR = "FLUO_ROOT"
CUDA_LIB_VAR = "CUDA_LIB"

SINGLEPARTICLE_HOME = "SINGLEPARTICLE_HOME"
SPFLUO_VERSION = "0.0.1"

PICKING_MODULE = "picking"
AB_INITIO_MODULE = "ab_initio_reconstruction"
REFINEMENT_MODULE = "refinement"
UTILS_MODULE = "utils"
MANUAL_PICKING_MODULE = "manual_picking"
VISUALISATION_MODULE = "visualisation"
REFINEMENT_MODULE = "refinement"

PICKING_WORKING_DIR = "picking"
CROPPING_SUBDIR = "cropped"

PYTHON_VERSION = "3.10"

SPFLUO_CUDA_LIB = "SINGLEPARTICLE_CUDA_LIB"
