name: Publish wheel on tag and deploy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install devpi-client  # Install devpi-client

    - name: Authenticate and upload to devpi
      run: |
        devpi use https://pypi.spfluo.ovh
        devpi login jean --password=${{ secrets.DEVPI_PASSWORD }}
        devpi use jean/dev
        devpi upload
      env:
        DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
  
  pip-compile-and-deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install pip-tools
      run: pip install uv

    - name: Run pip-compile
      run: uv pip compile requirements.in -o requirements.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add requirements.txt
        git commit -m 'Update requirements.txt' || echo "No changes to commit"
        git push
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/vps.key
        chmod 600 ~/.ssh/vps.key
        cat >>~/.ssh/config <<END
        Host vps
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/vps.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - name: Create directory on VPS and upload requirements.txt
      run: |
        export TAG=${{ github.ref_name }}
        ssh vps mkdir -p /var/www/downloads/requirements/$TAG
        echo "Copying requirements.txt to /var/www/downloads/requirements/$TAG/"
        scp requirements.txt vps:/var/www/downloads/requirements/$TAG/requirements.txt

    - name: Update latest symlink on VPS
      run: |
        export TAG=${{ github.ref_name }}
        ssh vps rm -r /var/www/downloads/requirements/latest
        ssh vps ln -s /var/www/downloads/requirements/$TAG /var/www/downloads/requirements/latest
