name: Publish wheel on tag and deploy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install devpi-client  # Install devpi-client

    - name: Authenticate and upload to devpi
      run: |
        devpi use https://pypi.spfluo.ovh
        devpi login jean --password=${{ secrets.DEVPI_PASSWORD }}
        devpi use jean/dev
        devpi upload
      env:
        DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
  
  pip-compile-and-deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install pip-tools
      run: pip install uv

    - name: Run pip-compile
      run: |
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-unknown-linux-gnu.txt --upgrade --python-version 3.11 --python-platform x86_64-unknown-linux-gnu
        echo spfluo-app | uv pip compile - -o requirements-cp311-aarch64-apple-darwin.txt --upgrade --python-version 3.11 --python-platform aarch64-apple-darwin
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-apple-darwin.txt --upgrade --python-version 3.11 --python-platform x86_64-apple-darwin
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-pc-windows-msvc.txt --upgrade --python-version 3.11 --python-platform x86_64-pc-windows-msvc

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add requirements*.txt
        git commit -m 'Update requirements.txt' || echo "No changes to commit"
        git push origin HEAD:main  # Push changes to the main branch
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/vps.key
        chmod 600 ~/.ssh/vps.key
        cat >>~/.ssh/config <<END
        Host vps
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/vps.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    
    - name: Set and modify TAG variable
      run: |
        TAG=${{ github.ref_name }}
        TAG=${TAG#v}
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Create directory on VPS and upload requirements.txt
      run: |
        ssh vps mkdir -p /var/www/downloads/requirements/$TAG
        echo "Copying requirements.txt to /var/www/downloads/requirements/$TAG/"
        scp requirements*.txt vps:/var/www/downloads/requirements/$TAG/
        echo "requirements.txt available at https://downloads.spfluo.ovh/requirements/$TAG/requirements-cp311-x86_64-unknown-linux-gnu.txt"

    - name: Update latest symlink on VPS
      run: |
        ssh vps rm -r /var/www/downloads/requirements/latest
        ssh vps ln -s /var/www/downloads/requirements/$TAG /var/www/downloads/requirements/latest
        echo "requirements.txt also available at https://downloads.spfluo.ovh/requirements/latest/requirements-cp311-x86_64-unknown-linux-gnu.txt"
