name: Build and publish docs

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install hatch
        run: pip install hatch
      
      - name: Build docs
        run: hatch run docs:build
      
      - name: Create archive
        run: tar -c -f site.tar.gz -C docs/build/html -z .
      
      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.tar.gz
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/vps.key
          chmod 600 ~/.ssh/vps.key
          cat >>~/.ssh/config <<END
          Host vps
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/vps.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Upload site to VPS
        run: |
          scp site.tar.gz vps:site.tar.gz
          ssh vps tar -xzvf site.tar.gz -C /var/www/docs --overwrite
