name: Publish wheel on tag and deploy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install devpi-client  # Install devpi-client

    - name: Authenticate and upload to devpi
      run: |
        devpi use https://pypi.spfluo.ovh
        devpi login jean --password=${{ secrets.DEVPI_PASSWORD }}
        devpi use jean/dev
        devpi upload
      env:
        DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
  
  pip-compile-and-deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-python-uv

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install pip-tools
      run: pip install uv

    - name: Run pip-compile
      run: |
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-unknown-linux-gnu.txt -q --upgrade --python-version 3.11 --python-platform x86_64-unknown-linux-gnu
        echo spfluo-app | uv pip compile - -o requirements-cp311-aarch64-apple-darwin.txt -q --upgrade --python-version 3.11 --python-platform aarch64-apple-darwin
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-apple-darwin.txt -q --upgrade --python-version 3.11 --python-platform x86_64-apple-darwin
        echo spfluo-app | uv pip compile - -o requirements-cp311-x86_64-pc-windows-msvc.txt -q --upgrade --python-version 3.11 --python-platform x86_64-pc-windows-msvc

    - name: Upload requirements files
      uses: actions/upload-artifact@v4
      with:
        name: requirements
        path: requirements*.txt
        retention-days: 1

  build-executable:
    needs: pip-compile-and-deploy
    runs-on: windows-latest
    env:
      PYAPP_VERSION: "0.22.0"
      PYAPP_PROJECT_NAME: "spfluo-app"
      PYAPP_PROJECT_VERSION: "0.1.1"
      PYAPP_PROJECT_DEPENDENCY_FILE: "${{ github.workspace }}/requirements-cp311-x86_64-pc-windows-msvc.txt"
      PYAPP_IS_GUI: 1
      PYAPP_PIP_EXTRA_ARGS: "--index-url https://pypi.spfluo.ovh/jean/dev/+simple"
      PYAPP_EXEC_SCRIPT: "${{ github.workspace }}/src/spfluo_app/__main__.py"
      PYAPP_PYTHON_VERSION: "3.11"
      PYAPP_UV_ENABLED: 1 
      TARGET_DIR: "${{ github.workspace }}/target"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Cache cargo target directory
      uses: actions/cache@v4
      with:
        path: "${{ github.workspace }}/target"
        key: pyapp-${{ PYAPP_VERSION }}-cargo-target
    
    - name: Download requirements.txt
      uses: actions/download-artifact@v4
      with:
        name: requirements

    - name: Download pyapp Source
      run: |
        Invoke-WebRequest -Uri "https://github.com/ofek/pyapp/releases/download/v$env:PYAPP_VERSION/source.tar.gz" -OutFile 'pyapp-source.tar.gz'
      shell: pwsh

    - name: Extract pyapp Source
      run: tar -xzf pyapp-source.tar.gz
      shell: pwsh

    - name: Build the Project
      env:
        RUST_BACKTRACE: "full"
        CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
      run: |
        Set-Location -Path "pyapp-v$env:PYAPP_VERSION"
        cargo build --release --target-dir $env:TARGET_DIR
        Move-Item -Path "$env:TARGET_DIR/release/pyapp.exe" -Destination "${{ github.workspace }}/spfluo-app.exe" -Force
      shell: pwsh
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: spfluo-app.exe
        retention-days: 1
  
  create-release:
    needs: [pip-compile-and-deploy, build-executable]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          requirements/requirements*.txt 
          executable/spfluo-app.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}