name: Publish wheel on tag and deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      spfluo-app-version: ${{ steps.version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install devpi-client

    - name: Authenticate and upload to devpi
      run: |
        devpi use https://pypi.spfluo.ovh
        devpi login jean --password=${{ secrets.DEVPI_PASSWORD }}
        devpi use jean/dev
        devpi upload
      env:
        DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
    
    - name: Get spfluo-app version
      id: version
      run: |
        pip install hatch
        echo "version=$(hatch version)" >> "$GITHUB_OUTPUT"
  
  publish-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [napari-bbox, napari-spfluo, scipion-app, scipion-fluo, scipion-fluo-singleparticle, scipion-pyworkflow, spfluo]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install devpi-client

    - name: Authenticate and upload to devpi
      run: |
        cd packages/${{ matrix.package }}
        devpi use https://pypi.spfluo.ovh
        devpi login jean --password=${{ secrets.DEVPI_PASSWORD }}
        devpi use jean/dev
        devpi upload
      env:
        DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
  
  compile-requirements:
    runs-on: ubuntu-latest
    needs: [publish, publish-packages]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-cache
    
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache

    - name: Install pip-tools
      run: pip install uv

    - name: Run pip-compile
      run: >
        uv pip compile pyproject.toml
        -o requirements.txt
        --universal
        -i https://pypi.spfluo.ovh/jean/dev/+simple
        --emit-index-url
        --no-sources
    
    - name: Run pip-compile gpu
      run: >
        uv pip compile pyproject.toml
        -o requirements-gpu.txt
        --universal
        -i https://pypi.spfluo.ovh/jean/dev-pytorch-cu124/+simple/  # torch is in the deps we need a custom index to enable CUDA
        --emit-index-url
        --no-sources
    
    - name: Append to requirements spfluo-app
      run: |
        REQUIREMENT_FILE=$(ls requirements*.txt | head -n 1)
        echo "spfluo-app==${{ needs.publish.outputs.spfluo-app-version }}" >> $REQUIREMENT_FILE

    - name: Upload requirements files
      uses: actions/upload-artifact@v4
      with:
        name: requirements
        path: requirements.txt
        retention-days: 1
    
    - name: Upload requirements files gpu
      uses: actions/upload-artifact@v4
      with:
        name: requirements-gpu
        path: requirements-gpu.txt
        retention-days: 1

  build-executable:
    needs: [compile-requirements]
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86_64-pc-windows-msvc]
        gpu: [false, true]
    
    env:
      PYAPP_VERSION: "0.22.0"
      PYAPP_PROJECT_NAME: "spfluo-app"
      PYAPP_PROJECT_VERSION: ${{ needs.publish.outputs.spfluo-app-version }}
      PYAPP_PROJECT_DEPENDENCY_FILE: "${{ github.workspace }}/requirements.txt"
      PYAPP_IS_GUI: 1
      PYAPP_EXEC_SCRIPT: "${{ github.workspace }}/src/spfluo_app/__main__.py"
      PYAPP_PYTHON_VERSION: "3.11"
      python_version: "11"
      PYAPP_UV_ENABLED: 1 
      TARGET_DIR: "${{ github.workspace }}/target"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Define gpu vars
      shell: pwsh
      run: |
        if ($${{ matrix.gpu }}) {
            echo "PYAPP_PIP_EXTRA_ARGS=--index-url=https://pypi.spfluo.ovh/jean/dev-pytorch-cu124/+simple" >> $env:GITHUB_ENV
            echo "PYAPP_PROJECT_DEPENDENCY_FILE=${{ github.workspace }}/requirements-gpu.txt" >> $env:GITHUB_ENV
            echo "GPU_SUFFIX=-gpu" >> $env:GITHUB_ENV
        } else {
            echo "PYAPP_PIP_EXTRA_ARGS=--index-url=https://pypi.spfluo.ovh/jean/dev/+simple" >> $env:GITHUB_ENV
            echo "PYAPP_PROJECT_DEPENDENCY_FILE=${{ github.workspace }}/requirements.txt" >> $env:GITHUB_ENV
            echo "GPU_SUFFIX=" >> $env:GITHUB_ENV
        }
        
    - name: Download requirements.txt
      uses: actions/download-artifact@v4
      with:
        name: requirements${{ env.GPU_SUFFIX }}

    - name: Download pyapp Source
      run: |
        Invoke-WebRequest -Uri "https://github.com/ofek/pyapp/releases/download/v$env:PYAPP_VERSION/source.tar.gz" -OutFile 'pyapp-source.tar.gz'
      shell: pwsh

    - name: Extract pyapp Source
      run: tar -xzf pyapp-source.tar.gz
      shell: pwsh

    - name: Build the Project
      env:
        RUST_BACKTRACE: "full"
        CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
      run: |
        Set-Location -Path "pyapp-v$env:PYAPP_VERSION"
        cargo build --release --target-dir $env:TARGET_DIR
        Move-Item -Path "$env:TARGET_DIR/release/pyapp.exe" -Destination "${{ github.workspace }}/spfluo-app$env:GPU_SUFFIX.exe" -Force
      shell: pwsh
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable${{ env.GPU_SUFFIX }}
        path: spfluo-app${{ env.GPU_SUFFIX }}.exe
        retention-days: 1
      
  create-release:
    needs: [compile-requirements, build-executable]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          requirements*/requirements*.txt 
          executable*/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}